---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: hs@tst2.ir     # letsencrypt notification email
    preferredChain: ""
    privateKeySecretRef:
      name: acme-issuer-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx      # Ingress class

